---
collections:
  - name: community.docker
    version: 5.0.3
  - name: community.general
    version: 12.1.0
roles:
  - name: geerlingguy.docker
    version: 7.9.0
  - name: geerlingguy.mysql
    version: 6.0.0
