---
collections:
  - name: community.docker
    version: 5.0.5
  - name: community.general
    version: 12.2.0
roles:
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.mysql
    version: 6.2.0
